/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullhouseprojectgui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;

/**
 *
 * @author Menno
 */
public class FinaleTafel extends javax.swing.JFrame {
    String t_code;
    /**
     * Creates new form FinaleTafel
     */
    public FinaleTafel() {
        initComponents();
        ModelItemToernooi toer = (ModelItemToernooi) Toernooi.ToernooiLijst.getSelectedValue();
        t_code = toer.id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        finaleTafel = new javax.swing.JList();
        eerste = new javax.swing.JRadioButton();
        tweede = new javax.swing.JRadioButton();
        derde = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Finaletafel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        prijzenGeld = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(finaleTafel);

        buttonGroup1.add(eerste);
        eerste.setText("Eerste");

        buttonGroup1.add(tweede);
        tweede.setText("Tweede");

        buttonGroup1.add(derde);
        derde.setText("Derde");

        jLabel1.setText("Selecteer de plaats");

        jButton1.setText("Selecteer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Fullhouse Manager");

        Finaletafel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Finaletafel.setText("Finaletafel");

        jScrollPane2.setViewportView(prijzenGeld);

        jLabel3.setText("Speler");

        jLabel4.setText("Prijzengeld");

        jButton2.setText("Terug");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eerste)
                                    .addComponent(tweede)
                                    .addComponent(derde)
                                    .addComponent(jLabel1))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(Finaletafel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Finaletafel)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(10, 10, 10)
                            .addComponent(eerste)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tweede)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(derde)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     DefaultListModel model2 = new DefaultListModel();
       ModelItem model = (ModelItem) FinaleTafel.finaleTafel.getSelectedValue();
       
        String plaatsQuery = "Update Toernooi set 1e = ? where t_code =?";
        String prijzenGeld = "select sum(inschrijfGeld * aantalSpelers) as prijsgeld from Toernooi where t_code =?";
        String prijzenGeld2 = "Update Toernooi set 2e = ? where t_code =?";
        String prijzenGeld3 = "Update Toernooi set 3e = ? where t_code =?";
        
        try {
            PreparedStatement stat = (PreparedStatement) FullhouseProjectGui.con.prepareStatement(plaatsQuery);
            PreparedStatement prijsGeld = (PreparedStatement) FullhouseProjectGui.con.prepareStatement(prijzenGeld);
            PreparedStatement prijs2stat = (PreparedStatement) FullhouseProjectGui.con.prepareStatement(prijzenGeld2);
            PreparedStatement prijs3stat = (PreparedStatement) FullhouseProjectGui.con.prepareStatement(prijzenGeld3);
            prijsGeld.setString(1, t_code);
            ResultSet rs = prijsGeld.executeQuery();
            rs.first();
            int Geld = rs.getInt("prijsgeld");
            
            if (FinaleTafel.eerste.isSelected())
                    {
            ModelItemPrijsgeld prijs = new ModelItemPrijsgeld();
             stat.setString(1, model.s_code);
             stat.setString(2, t_code);
             prijs.naam = model.naam;
             int eersteGeld = (int) (Geld * 0.4);
             prijs.prijsgeld = eersteGeld;
             model2.addElement(prijs);
             stat.executeUpdate();
            }
            if (FinaleTafel.tweede.isSelected()){
                ModelItemPrijsgeld prijs2 = new ModelItemPrijsgeld();
             prijs2stat.setString(1, model.s_code);
             prijs2stat.setString(2, t_code);
             prijs2.naam = model.naam;
             int tweedeGeld= (int) (Geld * 0.25);
             prijs2.prijsgeld = tweedeGeld;
             model2.addElement(prijs2);
             prijs2stat.executeUpdate();
            }
            if (FinaleTafel.derde.isSelected()){
                ModelItemPrijsgeld prijs3 = new ModelItemPrijsgeld();
             prijs3stat.setString(1, model.s_code);
             prijs3stat.setString(2, t_code);
             prijs3.naam = model.naam;
             int derdeGeld = (int) (Geld * 0.1);
              prijs3.prijsgeld = derdeGeld;
             model2.addElement(prijs3);
             prijs3stat.executeUpdate();
            }
            
            FinaleTafel.prijzenGeld.setModel(model2);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinaleTafel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinaleTafel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinaleTafel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinaleTafel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FinaleTafel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Finaletafel;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JRadioButton derde;
    public static javax.swing.JRadioButton eerste;
    public static javax.swing.JList finaleTafel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JList prijzenGeld;
    public static javax.swing.JRadioButton tweede;
    // End of variables declaration//GEN-END:variables
}
