/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullhouseprojectgui;

import static fullhouseprojectgui.SpelerInvoerFrame.MasterclassLeraarT;
import static fullhouseprojectgui.SpelerInvoerFrame.WoonplaatsT;
import static fullhouseprojectgui.SpelerInvoerFrame.adresT;
import static fullhouseprojectgui.SpelerInvoerFrame.emailT;
import static fullhouseprojectgui.SpelerInvoerFrame.naamT;
import static fullhouseprojectgui.SpelerInvoerFrame.postcodeT;
import static fullhouseprojectgui.SpelerInvoerFrame.ratingT;
import static fullhouseprojectgui.SpelerInvoerFrame.telefoonnummerT;
import javax.swing.JOptionPane;

/**
 *
 * @author Roy
 */
public class SpelerWijzigFrame extends javax.swing.JFrame {

    /**
     * Creates new form SpelerWijzigFrame
     */
    public SpelerWijzigFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldWijzigSpelerNaam = new javax.swing.JTextField();
        jTextFieldSpelersAdres = new javax.swing.JTextField();
        jTextFieldSpelersPostcode = new javax.swing.JTextField();
        jTextFieldSpelersWoonplaats = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelSpelersWonplaats = new javax.swing.JLabel();
        jTextFieldSpelersEmail = new javax.swing.JTextField();
        jTextFieldTelefoon = new javax.swing.JTextField();
        jTextFieldMasterclass = new javax.swing.JTextField();
        jTextFieldRating = new javax.swing.JTextField();
        jLabelSpelersEmail = new javax.swing.JLabel();
        jLabelSpelersTelefoon = new javax.swing.JLabel();
        jLabelSpelersLeraar = new javax.swing.JLabel();
        jLabelSpelersRating = new javax.swing.JLabel();
        jButtonWijzigCommit = new javax.swing.JButton();
        swHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Fullhouse Manager");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Informatie van spelers wijzigen");

        jLabel2.setText("Naam");

        jLabel3.setText("Adres");

        jLabel5.setText("Postcode");

        jLabelSpelersWonplaats.setText("Woonplaats");

        jLabelSpelersEmail.setText("Emailadres");

        jLabelSpelersTelefoon.setText("Telefoonnummer");

        jLabelSpelersLeraar.setText("Masterclass Leraar");

        jLabelSpelersRating.setText("Rating");

        jButtonWijzigCommit.setText("Wijzigen");
        jButtonWijzigCommit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonWijzigCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWijzigCommitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabelSpelersWonplaats))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldWijzigSpelerNaam, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jTextFieldSpelersAdres)
                            .addComponent(jTextFieldSpelersPostcode)
                            .addComponent(jTextFieldSpelersWoonplaats))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelSpelersLeraar, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelSpelersRating)
                                    .addGap(18, 18, 18)))
                            .addComponent(jLabelSpelersTelefoon)
                            .addComponent(jLabelSpelersEmail))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMasterclass, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jTextFieldRating)
                            .addComponent(jTextFieldTelefoon)
                            .addComponent(jTextFieldSpelersEmail)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jButtonWijzigCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldWijzigSpelerNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldSpelersEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSpelersEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSpelersAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTelefoon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSpelersTelefoon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSpelersPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldMasterclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSpelersLeraar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSpelersWoonplaats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSpelersWonplaats)
                    .addComponent(jTextFieldRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSpelersRating))
                .addGap(26, 26, 26)
                .addComponent(jButtonWijzigCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        swHome.setText("Terug");
        swHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        swHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(118, 118, 118)
                                .addComponent(swHome)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(160, 160, 160))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(swHome)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void swHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swHomeActionPerformed

       this.dispose();
    }//GEN-LAST:event_swHomeActionPerformed

    private void jButtonWijzigCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWijzigCommitActionPerformed
        
        String naam = jTextFieldWijzigSpelerNaam.getText();
        String postcode = jTextFieldSpelersPostcode.getText();
        String rating = jTextFieldRating.getText();
        String telefoonnummer = jTextFieldTelefoon.getText();
        String email = jTextFieldSpelersEmail.getText();
        String adres = jTextFieldSpelersAdres.getText();
        String woonplaats = jTextFieldSpelersWoonplaats.getText();
        String masterclassleraar = jTextFieldMasterclass.getText();
        
        int postcodelengte = postcode.length();
        int mcleraarlengte = masterclassleraar.length();
        
        if((naam.isEmpty()) || (adres.isEmpty()) || (postcode.isEmpty()) || (woonplaats.isEmpty()) || (email.isEmpty())
        || (telefoonnummer.isEmpty()) || (masterclassleraar.isEmpty()) || (rating.isEmpty()) || (!email.contains("@")) 
        || (!email.contains(".")) || (!telefoonnummer.matches("[0-9]+")) || (!rating.matches("[0-9]+")) || (postcodelengte > 7) 
        || (mcleraarlengte > 1) || (naam.matches(("[0-9]+"))) || (woonplaats.matches(("[0-9]+")))){
            
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Speler is succesvol gewijzigd");
            FullhouseProjectGui.spelerWijzigen();
        }
         
        if(naam.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Invoer mag niet leeg zijn", "Naam", JOptionPane.CANCEL_OPTION);
        }
        if(naam.matches(("[0-9]+"))){
            JOptionPane.showMessageDialog(rootPane, "Invoer mag geen cijfers bevatten", "Naam", JOptionPane.CANCEL_OPTION);
        }
        if(adres.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Invoer mag niet leeg zijn", "Adres", JOptionPane.CANCEL_OPTION);
        }
        if(postcode.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Invoer mag niet leeg zijn", "Postcode", JOptionPane.CANCEL_OPTION);
        }
        if(woonplaats.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Invoer mag niet leeg zijn", "Woonplaats", JOptionPane.CANCEL_OPTION);
        }
        if(woonplaats.matches(("[0-9]+"))){
            JOptionPane.showMessageDialog(rootPane, "Invoer mag geen cijfers bevatten", "Woonplaats", JOptionPane.CANCEL_OPTION);
        }
        if(email.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Invoer mag niet leeg zijn", "E-mail", JOptionPane.CANCEL_OPTION);
        }
        if((!email.contains("@")) || (!email.contains("."))){
            JOptionPane.showMessageDialog(rootPane, "Dit is geen valide e-mail", "E-mail" , JOptionPane.CANCEL_OPTION);
        }
        if(telefoonnummer.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Invoer mag niet leeg zijn", "Telefoonnummer", JOptionPane.CANCEL_OPTION);
        }
        if(!telefoonnummer.matches("[0-9]+")){
            JOptionPane.showMessageDialog(rootPane, "Invoer mag geen letters bevatten", "Telefoonnummer", JOptionPane.CANCEL_OPTION);
        }
        if(masterclassleraar.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Invoer mag niet leeg zijn", "Masterclass Leraar", JOptionPane.CANCEL_OPTION);
        }
        if(mcleraarlengte > 1){
            JOptionPane.showMessageDialog(rootPane, "Dit is geen valide invoer", "Masterclass Leraar", JOptionPane.CANCEL_OPTION);
        }
        if(rating.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Invoer mag niet leeg zijn", "Rating", JOptionPane.CANCEL_OPTION);
        }
        if(!rating.matches("[0-9]+")){
            JOptionPane.showMessageDialog(rootPane, "Invoer mag geen letters bevatten", "Rating", JOptionPane.CANCEL_OPTION);
        }
        if(postcodelengte > 7){
            JOptionPane.showMessageDialog(rootPane, "Dit is geen valide postcode", "Postcode", JOptionPane.CANCEL_OPTION);
        }
        
    }//GEN-LAST:event_jButtonWijzigCommitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpelerWijzigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpelerWijzigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpelerWijzigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpelerWijzigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SpelerWijzigFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonWijzigCommit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelSpelersEmail;
    private javax.swing.JLabel jLabelSpelersLeraar;
    private javax.swing.JLabel jLabelSpelersRating;
    private javax.swing.JLabel jLabelSpelersTelefoon;
    private javax.swing.JLabel jLabelSpelersWonplaats;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTextFieldMasterclass;
    public static javax.swing.JTextField jTextFieldRating;
    public static javax.swing.JTextField jTextFieldSpelersAdres;
    public static javax.swing.JTextField jTextFieldSpelersEmail;
    public static javax.swing.JTextField jTextFieldSpelersPostcode;
    public static javax.swing.JTextField jTextFieldSpelersWoonplaats;
    public static javax.swing.JTextField jTextFieldTelefoon;
    public static javax.swing.JTextField jTextFieldWijzigSpelerNaam;
    private javax.swing.JButton swHome;
    // End of variables declaration//GEN-END:variables
}
